package Main;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CargaDatos.java
 *
 * Created on 25/03/2011, 18:11:51
 */

/**
 *
 * @author user
 */
public class CargaDatos extends javax.swing.JFrame
{


    int nroLlamada;
    String[] datos;
    String cantidad;
    int[] cantidadXIntervalo;
    double[] intervalo = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14 };
    int llamadas;
    double frecEsperada = 0;
    double[] frecObservada = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    double[] frecObsAcum = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    double[] frecEspAcum = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    double[] difFrec = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };


    //String[] intervalos;
    

    /** Creates new form CargaDatos */

    public CargaDatos()
    {
        
        initComponents();
        cantidad = "";
        llamadas = 0;
        datos = new String[14];
        cantidadXIntervalo = new int[14];
        nroLlamada = 1;
        tNroLlamada.setText(String.valueOf(nroLlamada));
        String[] intervalos = { "6-7", "7-8", "8-9", "9-10", "11-12", "12-13", "13-14", "14-15", "15-16", "16-17", "17-18", "18-19", "19-20" };


    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bPruebaKS = new javax.swing.JButton();
        tPrueba = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jbtnCargadora = new javax.swing.JButton();
        jbtnCargadora1 = new javax.swing.JButton();
        jbtnCargadora2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lNroLlamada = new javax.swing.JLabel();
        tNroLlamada = new javax.swing.JTextField();
        cBIntervalos = new javax.swing.JComboBox();
        lIntervalo = new javax.swing.JLabel();
        bGrabar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        bListar = new javax.swing.JButton();
        bHisto = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        bPruebaChi = new javax.swing.JButton();
        tPruebaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bPruebaKS.setText("Prueba K-S");
        bPruebaKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPruebaKSActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 10));
        jLabel3.setText("(para mas de 50 grados de libertad - nivel confianza 90%)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bPruebaKS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPruebaKS)
                    .addComponent(tPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tArea.setColumns(20);
        tArea.setRows(5);
        jScrollPane1.setViewportView(tArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnCargadora.setText("llamadas recibidas");
        jbtnCargadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargadoraActionPerformed(evt);
            }
        });

        jbtnCargadora1.setText("ingresos a telefonica");
        jbtnCargadora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargadora1ActionPerformed(evt);
            }
        });

        jbtnCargadora2.setText("ejemplo");
        jbtnCargadora2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargadora2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Datos ya cargados:");

        jButton1.setText("ingresos al supermercado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCargadora1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnCargadora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jbtnCargadora2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCargadora)
                    .addComponent(jbtnCargadora2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnCargadora1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setName(""); // NOI18N

        lNroLlamada.setText("Nro Llamada");

        tNroLlamada.setEnabled(false);

        cBIntervalos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "06-07", "07-08", "08-09", "09-10", "10-11", "11-12", "12-13", "13-14", "14-15", "15-16", "16-17", "17-18", "18-19", "19-20" }));

        lIntervalo.setText("Intervalo");

        bGrabar.setText("Grabar");
        bGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGrabarActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingreso Manual:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lIntervalo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(cBIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lNroLlamada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNroLlamada, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bGrabar))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNroLlamada)
                    .addComponent(tNroLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cBIntervalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lIntervalo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGrabar)
                .addGap(5, 5, 5))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bListar.setText("Listar");
        bListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bListarActionPerformed(evt);
            }
        });

        bHisto.setText("Histograma");
        bHisto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistoActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bListar)
                    .addComponent(bHisto)
                    .addComponent(bBorrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bHisto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bPruebaChi.setText("Prueba Chi 2");
        bPruebaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPruebaChiActionPerformed(evt);
            }
        });

        tPruebaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPruebaChiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10));
        jLabel4.setText("(13 grados de lib - alfa 0,1)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPruebaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bPruebaChi)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bPruebaChi)
                .addGap(18, 18, 18)
                .addComponent(tPruebaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Trabajo Práctico Numero 2 - Simulación");

        jLabel6.setText("David Coppa");

        jLabel7.setText("Manuel Muñoz");

        jLabel8.setText("Ezequiel Fernandez");

        jLabel9.setText("Victor Gutierrez");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel10.setText("Integrantes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)
                                .addComponent(jLabel6)
                                .addComponent(jLabel10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGrabarActionPerformed
        // TODO add your handling code here:
        nroLlamada ++;
        tNroLlamada.setText(String.valueOf(nroLlamada));
        String inter = (String)cBIntervalos.getSelectedItem();

        switch (cBIntervalos.getSelectedIndex())
        {
            case 0:
                cantidadXIntervalo[0]++;
                break;
            case 1:
                cantidadXIntervalo[1]++;
                break;
            case 2:
                cantidadXIntervalo[2]++;
                break;
            case 3:
                cantidadXIntervalo[3]++;
                break;
            case 4:
                cantidadXIntervalo[4]++;
                break;
            case 5:
                cantidadXIntervalo[5]++;
                break;
            case 6:
                cantidadXIntervalo[6]++;
                break;
            case 7:
                cantidadXIntervalo[7]++;
                break;
            case 8:
                cantidadXIntervalo[8]++;
                break;
            case 9:
                cantidadXIntervalo[9]++;
                break;
            case 10:
                cantidadXIntervalo[10]++;
                break;
            case 11:
                cantidadXIntervalo[11]++;
                break;
            case 12:
                cantidadXIntervalo[12]++;
                break;
            case 13:
                cantidadXIntervalo[13]++;
                break;
        }
      
        
    }//GEN-LAST:event_bGrabarActionPerformed

    private void bListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bListarActionPerformed
        // TODO add your handling code here:
        for (int i=0; i<14; i++)
        {
        cantidad += String.valueOf("Intervalo: "+ i + " - Cantidad de llamadas: " + cantidadXIntervalo[i]) + "\n";
        }
        tArea.setText(String.valueOf(cantidad));
        llamadas =0;// Integer.parseInt(tNroLlamada.getText());
        //verSiEsChiCuadrado();
        
    }//GEN-LAST:event_bListarActionPerformed
    int m;
    public void verSiEsChiCuadrado()
    {
    //    int m=62;//Integer.parseInt(tNroLlamada.getText()); // valores de numero de llamada
        int k=14; //intervalos
        float fEsp=m/k;
        
        float calculo=0;
        float resultado=0;
        System.out.println("valor de m: "+m);
        System.out.println("valor de fEsp: "+fEsp);
        float total=0;
        for (int i=0; i<k; i++)
        {
            calculo= (fEsp-cantidadXIntervalo[i]);
            System.out.println("calculo: "+calculo);
            resultado= (float) Math.pow(calculo,2);
            System.out.println("result: "+resultado+" cantidad intrvalo:  "+cantidadXIntervalo[i]);
            total=total+resultado;
            System.out.println("total: "+total);
        }
        float h=total/fEsp;
        System.out.println("valor de h: "+h);


        if (h<19.8119) //19.8119 es el valor de chicuadrado para n-1=13, y alfa=0.1
        {
         //   tArea.setText(String.valueOf(cantidad));
            //tArea.setText("datos:\n"+cantidad+"\n Uniforme");
            tPruebaChi.setText("Uniforme");
        }
        else
        {
            //tArea.setText("datos:\n"+cantidad+"\n NO uniforme");
            tPruebaChi.setText("No  uniforme");
        }
                  
    }


    //es para no tener que cargar en cada corrida los valores...
    public void cargadoraDeDatos(int x)
    {
        switch(x)
        {
            case 1:
                for (int i = 0; i < 14; i++)
                {
                    cantidadXIntervalo[i]=verCantidadMuestra1(i);
                    m=m+cantidadXIntervalo[i];
                }
                break;
            case 2:
                for (int i = 0; i < 14; i++)
                {
                    cantidadXIntervalo[i]=verCantidadMuestra2(i);
                    m=m+cantidadXIntervalo[i];
                }
                break;
            case 3:
                for (int i = 0; i < 14; i++) {
                    cantidadXIntervalo[i] = verCantidadMuestra3(i);
                    m = m + cantidadXIntervalo[i];
                }
                break;
            case 4:
                for (int i = 0; i < 14; i++) {
                    cantidadXIntervalo[i] = verCantidadMuestra4(i);
                    m = m + cantidadXIntervalo[i];
                }
                break;
        }
        
    }

    public int verCantidadMuestra1(int i)
    {
        int x=0;
        switch (i)
        {
            case 0:
                x=6;
                break;
            case 1:
                x=4;
                break;
            case 2:
                x=3;
                break;
            case 3:
                x=5;
                break;
            case 4:
                x=3;
                break;
            case 5:
                x=4;
                break;
            case 6:
                x=5;//
                break;
            case 7:
                x=4;
                break;
            case 8:
                x=6;
                break;
            case 9:
                x=5;
                break;
            case 10:
                x=5;
                break;
            case 11:
                x=2;
                break;
            case 12:
                x=5;
                break;
            case 13:
                x=5;
                break;
        }

        tNroLlamada.setText("62");

        return x;
    }

     public int verCantidadMuestra2(int i)
    {
        int x=0;
        switch (i)
        {
            case 0:
                x=2;
                break;
            case 1:
                x=5;
                break;
            case 2:
                x=8;
                break;
            case 3:
                x=5;
                break;
            case 4:
                x=3;
                break;
            case 5:
                x=0;
                break;
            case 6:
                x=2;//
                break;
            case 7:
                x=3;
                break;
            case 8:
                x=6;
                break;
            case 9:
                x=5;
                break;
            case 10:
                x=6;
                break;
            case 11:
                x=2;
                break;
            case 12:
                x=6;
                break;
            case 13:
                x=3;
                break;
        }


        tNroLlamada.setText("56");
        return x;
    }

     public int verCantidadMuestra3(int i)
    {
        int x=0;
        switch (i)
        {
            case 0:
                x=12;
                break;
            case 1:
                x=19;
                break;
            case 2:
                x=4;
                break;
            case 3:
                x=15;
                break;
            case 4:
                x=9;
                break;
            case 5:
                x=3;
                break;
            case 6:
                x=11;//
                break;
            case 7:
                x=15;
                break;
            case 8:
                x=5;
                break;
            case 9:
                x=6;
                break;
            case 10:
                x=17;
                break;
            case 11:
                x=8;
                break;
            case 12:
                x=10;
                break;
            case 13:
                x=7;
                break;
        }

        tNroLlamada.setText("131");

        return x;
    }

     public int verCantidadMuestra4(int i)
    {
        int x=0;
        switch (i)
        {
            case 0:
                x=12;
                break;
            case 1:
                x=53;
                break;
            case 2:
                x=2;
                break;
            case 3:
                x=72;
                break;
            case 4:
                x=35;
                break;
            case 5:
                x=3;
                break;
            case 6:
                x=23;//
                break;
            case 7:
                x=45;
                break;
            case 8:
                x=86;
                break;
            case 9:
                x=5;
                break;
            case 10:
                x=57;
                break;
            case 11:
                x=3;
                break;
            case 12:
                x=98;
                break;
            case 13:
                x=50;
                break;
        }

        tNroLlamada.setText("544");

        return x;
    }

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        tArea.setText("");
        cantidad="";
        nroLlamada = 0;
        frecEsperada =0;
        //tDuracion.setText("");
        tNroLlamada.setText("1");
        tPrueba.setText("");
        for (int i=0; i<14; i++){
        cantidadXIntervalo[i] = 0;
        frecObsAcum[i] = 0;
        frecEspAcum[i] = 0;
        difFrec[i] = 0;

        }
    }//GEN-LAST:event_bBorrarActionPerformed

    private void bHistoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistoActionPerformed
        // TODO add your handling code here:
        GraficoHistograma grafico = new GraficoHistograma(intervalo, cantidadXIntervalo);
        grafico.setSize(1024, 768);
        grafico.setVisible(true);
    }//GEN-LAST:event_bHistoActionPerformed

    private void bPruebaKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPruebaKSActionPerformed
        // Cantidad de llamadas ingresadas
        llamadas = Integer.parseInt(tNroLlamada.getText());

        //Guarda en un vector Double las frecuencias observadas
        for (int i=0; i<14; i++)
        {
            frecObservada[i] = (double) cantidadXIntervalo[i];
        }
        //Calculo frecuencia esperada
        frecEsperada = (double) llamadas/14;
        
        
        //Guarda en un vector Double las frecuencias observadas acumuladas
        int acum=0;
        for (int i=0; i<14; i++)
        {

            acum += cantidadXIntervalo[i];
            frecObsAcum[i] = (double) acum;
        }

        //Guarda en un vector Double las frecuencias esperadas acumuladas
        double acum2=0;
        for (int i=0; i<14; i++)
        {

            acum2 += frecEsperada;
            frecEspAcum[i] = acum2;
        }

        //Guarda en un vector Double las diferencias entre las frec. observadas acum. y las esperadas acum.
        for (int i=0; i<14; i++)
        {
            difFrec[i] = frecObsAcum[i] - frecEspAcum[i];
        }

        //Busca la diferencia con el mayor valor absoluto
        double mayor = difFrec[0];
        for (int i=0; i<14; i++)
        {

            if (difFrec[i]<0)
            {
                difFrec[i] = difFrec[i]*(-1);
            }
            if (mayor<difFrec[i])
            {
                mayor = difFrec[i];
            }
            

        }

        //tDuracion.setText(String.valueOf(mayor));

        //Calculo del nro para comparar con valor de tabla K-S con un nivel de confianza del 90%
        double comp = mayor/llamadas;
        double valorKS = (double) 1.22/Math.sqrt(llamadas);
        //Comparación para aceptar o rechazar prueba de distribución uniforme


        if (50 < llamadas) {
            if (comp < valorKS) {
                tPrueba.setText("Uniforme");
            } else {
                tPrueba.setText("No uniforme");
            }
        } else {
            tPrueba.setText("Error");
        }

        
;

    }//GEN-LAST:event_bPruebaKSActionPerformed

    
    //este metodo carga los datos solo...
    private void jbtnCargadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargadoraActionPerformed
        cargadoraDeDatos(1);
    }//GEN-LAST:event_jbtnCargadoraActionPerformed

    private void jbtnCargadora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargadora1ActionPerformed
        cargadoraDeDatos(2);
    }//GEN-LAST:event_jbtnCargadora1ActionPerformed

    private void jbtnCargadora2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargadora2ActionPerformed
        cargadoraDeDatos(4);
    }//GEN-LAST:event_jbtnCargadora2ActionPerformed

    private void tPruebaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPruebaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPruebaChiActionPerformed

    private void bPruebaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPruebaChiActionPerformed
        // TODO add your handling code here:
        verSiEsChiCuadrado();

    }//GEN-LAST:event_bPruebaChiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cargadoraDeDatos(3);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bGrabar;
    private javax.swing.JButton bHisto;
    private javax.swing.JButton bListar;
    private javax.swing.JButton bPruebaChi;
    private javax.swing.JButton bPruebaKS;
    private javax.swing.JComboBox cBIntervalos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCargadora;
    private javax.swing.JButton jbtnCargadora1;
    private javax.swing.JButton jbtnCargadora2;
    private javax.swing.JLabel lIntervalo;
    private javax.swing.JLabel lNroLlamada;
    private javax.swing.JTextArea tArea;
    private javax.swing.JTextField tNroLlamada;
    private javax.swing.JTextField tPrueba;
    private javax.swing.JTextField tPruebaChi;
    // End of variables declaration//GEN-END:variables

}
