/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 24/08/2009, 13:17:59
 */
package GUI;

import java.text.DecimalFormat;
import simulacion.CentroSalud;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    private CentroSalud centroSalud;
    private boolean nuevosDatos = true;
    private VectorSolucion ventanaSolucion;
    private VectorSolucion ventanaClientes;
    private Object[][] datosPaciente;
    private String[] nombresColumnasPacientes;

    /** Creates new form Main */
    public Main() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labLlamadasPerdidas = new javax.swing.JLabel();
        labTiempoPromedio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSimular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chkPersonas = new javax.swing.JCheckBox();
        txtPersonas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RapiPago");
        setResizable(false);

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 10))); // NOI18N
        panelDatos.setInheritsPopupMenu(true);

        btnClientes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(0, 153, 255));
        btnClientes.setText("Pacientes");
        btnClientes.setEnabled(false);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel6.setText("Llamadas perdidas:");

        labLlamadasPerdidas.setFont(new java.awt.Font("Calibri", 0, 12));
        labLlamadasPerdidas.setForeground(new java.awt.Color(0, 153, 204));
        labLlamadasPerdidas.setText("[Simular]");

        labTiempoPromedio.setFont(new java.awt.Font("Calibri", 0, 12));
        labTiempoPromedio.setForeground(new java.awt.Color(0, 153, 204));
        labTiempoPromedio.setText("[Simular]");

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel8.setText("Tiempo promedio en cola:");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTiempoPromedio)
                    .addComponent(labLlamadasPerdidas)))
            .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(labLlamadasPerdidas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labTiempoPromedio))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes))
        );

        btnSimular.setFont(new java.awt.Font("Calibri", 1, 14));
        btnSimular.setForeground(new java.awt.Color(255, 0, 0));
        btnSimular.setText("Simular");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18));
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Centro de Salud");

        chkPersonas.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        chkPersonas.setText("Cantidad de minutos:");
        chkPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPersonasActionPerformed(evt);
            }
        });

        txtPersonas.setFont(new java.awt.Font("Calibri", 0, 12));
        txtPersonas.setText("480");
        txtPersonas.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkPersonas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(btnSimular)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPersonas)
                    .addComponent(txtPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimular)
                .addGap(1, 1, 1)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed

    try {
        double minutos = Double.parseDouble(txtPersonas.getText());//)Integer.parseInt(txtPersonas.getText());
        centroSalud = new CentroSalud(minutos);
        centroSalud.simular();
        nuevosDatos = true;
        btnClientes.setEnabled(true);
        ventanaSolucion = new VectorSolucion(VectorSolucion.VECTOR_SOLUCION);
        ventanaSolucion.cargarDatos(centroSalud.getMatrizEstado(), centroSalud.getNombresColumnas());
        ventanaSolucion.setVisible(true);
        ventanaClientes = null;
        cargarDatos();
        panelDatos.setVisible(true);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresá números válidos", "Error", JOptionPane.ERROR_MESSAGE);

    } catch (OutOfMemoryError e) {
        JOptionPane.showMessageDialog(this, "No hay memoria suficiente =(", "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_btnSimularActionPerformed

private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
    if (nuevosDatos) {
        datosPaciente = centroSalud.getMatrizPacientes();
        nombresColumnasPacientes = centroSalud.getNombresColumnasClientes();
        nuevosDatos = false;
        if (ventanaClientes != null) {
            ventanaClientes.cargarDatos(datosPaciente, nombresColumnasPacientes);
            if (!ventanaClientes.isVisible()) {
                ventanaClientes.setVisible(true);
            }
        } else {
            mostrarClientes();
        }
    } else {
        ventanaClientes.setVisible(true);
    }
}//GEN-LAST:event_btnClientesActionPerformed

private void chkPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPersonasActionPerformed
    if (chkPersonas.isSelected()) {
        txtPersonas.setEnabled(true);

    } else {
        txtPersonas.setEnabled(false);
        txtPersonas.setText("480");
    }
}//GEN-LAST:event_chkPersonasActionPerformed

    private void mostrarClientes() {
        ventanaClientes = new VectorSolucion(VectorSolucion.VECTOR_DE_PACIENTES);
        ventanaClientes.cargarDatos(datosPaciente, nombresColumnasPacientes);
        ventanaClientes.setTitle("Comportamiento de los Pacientes");
        ventanaClientes.setVisible(true);
    }

    private void cargarDatos() {
        labLlamadasPerdidas.setText(String.valueOf(centroSalud.getCantidadLlamadasPerdidas()));
        DecimalFormat formato = new DecimalFormat("#.##");
        double tiempo = Double.valueOf(formato.format(centroSalud.getTiempoPromedioEspera()).replace(',', '.'));
        labTiempoPromedio.setText(String.valueOf(tiempo));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnSimular;
    private javax.swing.JCheckBox chkPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labLlamadasPerdidas;
    private javax.swing.JLabel labTiempoPromedio;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTextField txtPersonas;
    // End of variables declaration//GEN-END:variables
}
