
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 14-abr-2011, 19:59:16
 */
/**
 *
 * @author Administrador
 */
public class GUI extends javax.swing.JFrame {

    private GestorNumeroAleatorio g = new GestorNumeroAleatorio();
    private Object[] modeloIntervalos = {10, 25, 50, 75, 100};

    /** Creates new form GUI */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfMediaPoisson = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtNumAGenerarPoisson = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbIntervalosPoisson = new javax.swing.JComboBox(modeloIntervalos);
        jbSimularPoisson = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfMediaExponencial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtNumAGenerarExponencial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbIntervalosExponencial = new javax.swing.JComboBox(modeloIntervalos);
        jbSimularExponencial = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jrbSenoCoseno = new javax.swing.JRadioButton();
        jrbSumatoria = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSenCosen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSumatoria = new javax.swing.JTextArea();
        lCant = new javax.swing.JLabel();
        tfCantValoresSumatoria = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtNumAGenerarNormal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jcbIntervalosNormal = new javax.swing.JComboBox(modeloIntervalos);
        jbSimularNormal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jrbAditiva = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfAb = new javax.swing.JTextField();
        jtfAm = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtfMulM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfMulA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jrbMultiplicativa = new javax.swing.JRadioButton();
        jtfMixM = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtfMixB = new javax.swing.JTextField();
        jtfMixA = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jrbMixta = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jtfASemilla = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtfMulSemilla = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jtfMixSemilla = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtNumAGenerarCongruencia = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jcbIntervalosCongruencia = new javax.swing.JComboBox(modeloIntervalos);
        jbSimularCongruencia = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtfUniformeA = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtfUniformeB = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jtNumAGenerarUniforme = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jcbIntervalosUniforme = new javax.swing.JComboBox(modeloIntervalos);
        jbSimularUniforme = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlNumerosAleatoriosGenerados = new javax.swing.JList();
        jLabel27 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jfHistograma = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel8.setText("Ingrese la media (M(x)) que tendra la distribución :");

        jLabel9.setText("Ingrese la cantidad de numeros aleatorios que desea generar :");

        jLabel10.setText("Seleccione la cantidad de intervalos del histograma :");

        jbSimularPoisson.setText("Simular");
        jbSimularPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimularPoissonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbIntervalosPoisson, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtNumAGenerarPoisson)
                    .addComponent(tfMediaPoisson, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addComponent(jbSimularPoisson)
                .addGap(467, 467, 467))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMediaPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNumAGenerarPoisson)
                    .addComponent(jLabel9)
                    .addComponent(jbSimularPoisson))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jcbIntervalosPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        jTabbedPane1.addTab("Distribución Poisson", jPanel1);

        jLabel4.setText("Ingrese la media (M(x)) que tendra la distribución :");

        jLabel5.setText("Ingrese la cantidad de numeros aleatorios que desea generar :");

        jLabel6.setText("Seleccione la cantidad de intervalos del histograma :");

        jbSimularExponencial.setText("Simular");
        jbSimularExponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimularExponencialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfMediaExponencial)
                    .addComponent(jtNumAGenerarExponencial)
                    .addComponent(jcbIntervalosExponencial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addComponent(jbSimularExponencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(489, 489, 489))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMediaExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNumAGenerarExponencial)
                    .addComponent(jLabel5)
                    .addComponent(jbSimularExponencial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jcbIntervalosExponencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        jTabbedPane1.addTab("Distribución Exponencial", jPanel2);

        jLabel7.setText("Seleccione el método :");

        jrbSenoCoseno.setText("Seno - Coseno");
        jrbSenoCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSenoCosenoActionPerformed(evt);
            }
        });

        jrbSumatoria.setText("Sumatoria");
        jrbSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSumatoriaActionPerformed(evt);
            }
        });

        taSenCosen.setColumns(20);
        taSenCosen.setEditable(false);
        taSenCosen.setLineWrap(true);
        taSenCosen.setRows(3);
        taSenCosen.setTabSize(3);
        taSenCosen.setText("Este método NO recive parametros\nya que r1 y r2 son generados\naleatoriamente por el programa.");
        taSenCosen.setEnabled(false);
        jScrollPane1.setViewportView(taSenCosen);

        taSumatoria.setColumns(20);
        taSumatoria.setEditable(false);
        taSumatoria.setRows(3);
        taSumatoria.setTabSize(3);
        taSumatoria.setText("Ingrese la cantidad de numeros de distribucion\nuniforme a generar para generar cada numero\nde distribucion Normal.");
        taSumatoria.setEnabled(false);
        jScrollPane2.setViewportView(taSumatoria);

        lCant.setText("Cantidad de numeros de la sumatoria :");
        lCant.setEnabled(false);

        tfCantValoresSumatoria.setEnabled(false);

        jLabel12.setText("Ingrese la cantidad de numeros aleatorios que desea generar :");

        jLabel13.setText("Seleccione la cantidad de intervalos del histograma :");

        jbSimularNormal.setText("Simular");
        jbSimularNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimularNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jrbSumatoria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbSenoCoseno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbSimularNormal)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcbIntervalosNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtNumAGenerarNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(208, 208, 208))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lCant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCantValoresSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbSenoCoseno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNumAGenerarNormal)
                            .addComponent(jLabel12))
                        .addGap(83, 83, 83)
                        .addComponent(jbSimularNormal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbIntervalosNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbSumatoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lCant)
                            .addComponent(tfCantValoresSumatoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Distribución Normal", jPanel3);

        jPanel4.setEnabled(false);

        jrbAditiva.setText("Aditiva");
        jrbAditiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAditivaActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("La formula es: (semilla + b) mod m.");
        jTextField1.setEnabled(false);

        jLabel2.setText("Ingrese el valor de \"b\" :");
        jLabel2.setEnabled(false);

        jLabel3.setText("Ingrese el valor de \"m\" :");
        jLabel3.setEnabled(false);

        jtfAb.setEnabled(false);

        jtfAm.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jtfMulM.setEnabled(false);

        jLabel11.setText("Ingrese el valor de \"m\" :");
        jLabel11.setEnabled(false);

        jtfMulA.setEnabled(false);

        jLabel15.setText("Ingrese el valor de \"a\" :");
        jLabel15.setEnabled(false);

        jTextField11.setEditable(false);
        jTextField11.setText("La formula es: (a * semilla) mod m.");
        jTextField11.setEnabled(false);

        jrbMultiplicativa.setText("Multiplicativa");
        jrbMultiplicativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMultiplicativaActionPerformed(evt);
            }
        });

        jtfMixM.setEnabled(false);

        jLabel16.setText("Ingrese el valor de \"m\" :");
        jLabel16.setEnabled(false);

        jLabel17.setText("Ingrese el valor de \"b\" :");
        jLabel17.setEnabled(false);

        jtfMixB.setEnabled(false);

        jtfMixA.setEnabled(false);

        jLabel18.setText("Ingrese el valor de \"a\" :");
        jLabel18.setEnabled(false);

        jTextField15.setEditable(false);
        jTextField15.setText("La formula es: (a * semilla + b) mod m.");
        jTextField15.setEnabled(false);

        jrbMixta.setText("Mixta");
        jrbMixta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMixtaActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel19.setText("Ingrese el valor de la semilla :");
        jLabel19.setEnabled(false);

        jtfASemilla.setEnabled(false);

        jLabel20.setText("Ingrese el valor de la semilla :");
        jLabel20.setEnabled(false);

        jtfMulSemilla.setEnabled(false);

        jLabel21.setText("Ingrese el valor de la semilla :");
        jLabel21.setEnabled(false);

        jtfMixSemilla.setEnabled(false);

        jLabel14.setText("Ingrese la cantidad de numeros aleatorios que desea generar :");

        jLabel22.setText("Seleccione la cantidad de intervalos del histograma :");

        jbSimularCongruencia.setText("Simular");
        jbSimularCongruencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimularCongruenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfAm, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                            .addComponent(jtfAb, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                            .addComponent(jtfASemilla, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbAditiva)
                                .addGap(103, 103, 103)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfMulA, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                            .addComponent(jtfMulM, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                            .addComponent(jtfMulSemilla, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jrbMultiplicativa))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbIntervalosCongruencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtNumAGenerarCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jrbMixta))
                                    .addComponent(jtfMixA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(2, 2, 2)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMixM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfMixB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfMixSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jbSimularCongruencia))
                .addGap(263, 263, 263))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jrbMixta)
                        .addGap(16, 16, 16)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMixA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtfMixB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMixM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMixSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jrbAditiva)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfAb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfASemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jrbMultiplicativa)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMulA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMulM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfMulSemilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNumAGenerarCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbIntervalosCongruencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbSimularCongruencia))
                    .addComponent(jLabel22))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("Generador de Congruencia", jPanel4);

        jLabel1.setText("Genera numeros aleatorios uniformes U(a,b)");

        jLabel23.setText("Ingrese el valor de \"a\" :");

        jLabel24.setText("Ingrese el valor de \"b\" :");

        jLabel25.setText("Ingrese la cantidad de numeros aleatorios que desea generar :");

        jLabel26.setText("Seleccione la cantidad de intervalos del histograma :");

        jbSimularUniforme.setText("Simular");
        jbSimularUniforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimularUniformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfUniformeB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfUniformeA, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbIntervalosUniforme, 0, 88, Short.MAX_VALUE)
                            .addComponent(jbSimularUniforme, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jtNumAGenerarUniforme, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(655, 655, 655))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUniformeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUniformeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNumAGenerarUniforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jcbIntervalosUniforme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbSimularUniforme)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Distribución Uniforme", jPanel5);

        jlNumerosAleatoriosGenerados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "\"Aca pareceran los", "valores generados\"" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlNumerosAleatoriosGenerados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jlNumerosAleatoriosGenerados.setToolTipText("");
        jScrollPane3.setViewportView(jlNumerosAleatoriosGenerados);

        jLabel27.setText("Numeros Aleatorios Generados");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jfHistograma.setTitle("Histograma");
        jfHistograma.setFocusable(false);
        jfHistograma.setVisible(true);

        javax.swing.GroupLayout jfHistogramaLayout = new javax.swing.GroupLayout(jfHistograma.getContentPane());
        jfHistograma.getContentPane().setLayout(jfHistogramaLayout);
        jfHistogramaLayout.setHorizontalGroup(
            jfHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        jfHistogramaLayout.setVerticalGroup(
            jfHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jMenu1.setText("Simulacion");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Generadores");

        jMenuItem6.setText("Poisson");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Exponencial");
        jMenu2.add(jMenuItem7);

        jMenu4.setText("Normal");

        jMenuItem8.setText("Funcion Seno - Coseno");
        jMenu4.add(jMenuItem8);

        jMenuItem9.setText("Sumatoria");
        jMenu4.add(jMenuItem9);

        jMenu2.add(jMenu4);

        jMenu3.setText("Congruencia");

        jMenuItem4.setText("Mixta");
        jMenu3.add(jMenuItem4);

        jMenuItem2.setText("Multiplicativa");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Aditiva");
        jMenu3.add(jMenuItem3);

        jMenu2.add(jMenu3);

        jMenuItem5.setText("Uniforme");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfHistograma)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfHistograma))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenu1ActionPerformed

    private Object[] pasarALista(int CantDeValores, double[] numeros) {
        Object[] lista = new Object[CantDeValores];
        for (int i = 0; i < numeros.length; i++) {
            double d = numeros[i];
            lista[i] = d;
        }
        return lista;
    }

    private void jbSimularPoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimularPoissonActionPerformed

        int cantDeValores = Integer.parseInt(jtNumAGenerarPoisson.getText());
        double media = Double.parseDouble(tfMediaPoisson.getText());
        double[] numerosAleatorios = g.poisson(cantDeValores, media);

        Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
        jlNumerosAleatoriosGenerados.setListData(listaObject);

        graficarHistograma(calcularHistograma(numerosAleatorios,
                Integer.parseInt(jcbIntervalosCongruencia.getSelectedItem().toString()),
                true));

    }//GEN-LAST:event_jbSimularPoissonActionPerformed

    private void jbSimularExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimularExponencialActionPerformed

        int cantDeValores = Integer.parseInt(jtNumAGenerarExponencial.getText());
        double media = Double.parseDouble(tfMediaExponencial.getText());
        double[] numerosAleatorios = g.exponencial(cantDeValores, media);

        Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
        jlNumerosAleatoriosGenerados.setListData(listaObject);

        graficarHistograma(calcularHistograma(numerosAleatorios,
                Integer.parseInt(jcbIntervalosExponencial.getSelectedItem().toString()),
                false));
    }//GEN-LAST:event_jbSimularExponencialActionPerformed

    private void jrbSenoCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSenoCosenoActionPerformed

        if (jrbSenoCoseno.isSelected()) {
            jrbSumatoria.setSelected(false);
            taSumatoria.setEnabled(false);
            lCant.setEnabled(false);
            tfCantValoresSumatoria.setEnabled(false);

            taSenCosen.setEnabled(true);
        } else {
            taSenCosen.setEnabled(false);
        }


    }//GEN-LAST:event_jrbSenoCosenoActionPerformed

    private void jrbSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSumatoriaActionPerformed

        if (jrbSumatoria.isSelected()) {
            jrbSenoCoseno.setSelected(false);
            taSenCosen.setEnabled(false);

            taSumatoria.setEnabled(true);
            lCant.setEnabled(true);
            tfCantValoresSumatoria.setEnabled(true);
        } else {
            taSumatoria.setEnabled(false);
            lCant.setEnabled(false);
            tfCantValoresSumatoria.setEnabled(false);
        }

    }//GEN-LAST:event_jrbSumatoriaActionPerformed

    private void jbSimularNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimularNormalActionPerformed

        if ((!jrbSenoCoseno.isSelected()) && (!jrbSumatoria.isSelected())) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar uno de los dos métodos!!!",
                    "No hay seleccion de metodo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int cantDeValores = Integer.parseInt(jtNumAGenerarNormal.getText());



        if (jrbSenoCoseno.isSelected()) {

            double[] numerosAleatorios = g.normalSenoCoseno(cantDeValores);
            Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
            jlNumerosAleatoriosGenerados.setListData(listaObject);

            graficarHistograma(calcularHistograma(numerosAleatorios,
                    Integer.parseInt(jcbIntervalosNormal.getSelectedItem().toString()),
                    false));

        }
        if (jrbSumatoria.isSelected()) {

            int cantValoresSumatoria = Integer.parseInt(tfCantValoresSumatoria.getText());
            double[] numerosAleatorios = g.normalSumatoria(cantDeValores, cantValoresSumatoria);
            Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
            jlNumerosAleatoriosGenerados.setListData(listaObject);

            graficarHistograma(calcularHistograma(numerosAleatorios,
                    Integer.parseInt(jcbIntervalosNormal.getSelectedItem().toString()),
                    false));

        }

    }//GEN-LAST:event_jbSimularNormalActionPerformed

    private void deshabilitarCongruencia() {
        jrbAditiva.setSelected(false);
        jTextField1.setEnabled(false);
        jLabel2.setEnabled(false);
        jtfAb.setEnabled(false);
        jLabel3.setEnabled(false);
        jtfAm.setEnabled(false);
        jLabel19.setEnabled(false);
        jtfASemilla.setEnabled(false);

        jrbMultiplicativa.setSelected(false);
        jTextField11.setEnabled(false);
        jLabel15.setEnabled(false);
        jLabel11.setEnabled(false);
        jLabel20.setEnabled(false);
        jtfMulA.setEnabled(false);
        jtfMulM.setEnabled(false);
        jtfMulSemilla.setEnabled(false);


        jrbMixta.setSelected(false);
        jTextField15.setEnabled(false);
        jLabel18.setEnabled(false);
        jLabel17.setEnabled(false);
        jLabel16.setEnabled(false);
        jLabel21.setEnabled(false);
        jtfMixA.setEnabled(false);
        jtfMixB.setEnabled(false);
        jtfMixM.setEnabled(false);
        jtfMixSemilla.setEnabled(false);
    }

    private void jrbAditivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAditivaActionPerformed
        if (jrbAditiva.isSelected()) {
            deshabilitarCongruencia();
            jrbAditiva.setSelected(true);
            jTextField1.setEnabled(true);
            jLabel2.setEnabled(true);
            jtfAb.setEnabled(true);
            jLabel3.setEnabled(true);
            jtfAm.setEnabled(true);
            jLabel19.setEnabled(true);
            jtfASemilla.setEnabled(true);
        } else {
            deshabilitarCongruencia();
        }
    }//GEN-LAST:event_jrbAditivaActionPerformed

    private void jrbMultiplicativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMultiplicativaActionPerformed
        if (jrbMultiplicativa.isSelected()) {
            deshabilitarCongruencia();
            jrbMultiplicativa.setSelected(true);
            jTextField11.setEnabled(true);
            jLabel15.setEnabled(true);
            jLabel11.setEnabled(true);
            jLabel20.setEnabled(true);
            jtfMulA.setEnabled(true);
            jtfMulM.setEnabled(true);
            jtfMulSemilla.setEnabled(true);
        } else {
            deshabilitarCongruencia();
        }

    }//GEN-LAST:event_jrbMultiplicativaActionPerformed

    private void jrbMixtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMixtaActionPerformed
        if (jrbMixta.isSelected()) {
            deshabilitarCongruencia();
            jrbMixta.setSelected(true);
            jTextField15.setEnabled(true);
            jLabel18.setEnabled(true);
            jLabel17.setEnabled(true);
            jLabel16.setEnabled(true);
            jLabel21.setEnabled(true);
            jtfMixA.setEnabled(true);
            jtfMixB.setEnabled(true);
            jtfMixM.setEnabled(true);
            jtfMixSemilla.setEnabled(true);
        } else {
            deshabilitarCongruencia();
        }
    }//GEN-LAST:event_jrbMixtaActionPerformed

    private void jbSimularCongruenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimularCongruenciaActionPerformed

        if ((!jrbAditiva.isSelected()) && (!jrbMultiplicativa.isSelected()) && (!jrbMixta.isSelected())) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar uno de los dos métodos!!!",
                    "No hay seleccion de metodo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int cantDeValores = Integer.parseInt(jtNumAGenerarCongruencia.getText());
        double a = 0, b = 0, m = 0, semilla = 0;

        if (jrbAditiva.isSelected()) {

            b = Double.parseDouble(jtfAb.getText());
            m = Double.parseDouble(jtfAm.getText());
            semilla = Double.parseDouble(jtfASemilla.getText());

            double[] numerosAleatorios = g.CongruenciaAditiva(cantDeValores, b, m, semilla);
            Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
            jlNumerosAleatoriosGenerados.setListData(listaObject);

            graficarHistograma(calcularHistograma(numerosAleatorios,
                    Integer.parseInt(jcbIntervalosCongruencia.getSelectedItem().toString()),
                    true));

        }
        if (jrbMultiplicativa.isSelected()) {

            a = Double.parseDouble(jtfMulA.getText());
            m = Double.parseDouble(jtfMulM.getText());
            semilla = Double.parseDouble(jtfMulSemilla.getText());

            double[] numerosAleatorios = g.CongruenciaMultiplicativa(cantDeValores, a, m, semilla);
            Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
            jlNumerosAleatoriosGenerados.setListData(listaObject);

            graficarHistograma(calcularHistograma(numerosAleatorios,
                    Integer.parseInt(jcbIntervalosCongruencia.getSelectedItem().toString()),
                    true));

        }
        if (jrbMixta.isSelected()) {

            a = Double.parseDouble(jtfMixA.getText());
            b = Double.parseDouble(jtfMixB.getText());
            m = Double.parseDouble(jtfMixM.getText());
            semilla = Double.parseDouble(jtfMixSemilla.getText());

            double[] numerosAleatorios = g.CongruenciaMixta(cantDeValores, a, b, m, semilla);
            Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
            jlNumerosAleatoriosGenerados.setListData(listaObject);

            graficarHistograma(calcularHistograma(numerosAleatorios,
                    Integer.parseInt(jcbIntervalosCongruencia.getSelectedItem().toString()),
                    true));

        }

    }//GEN-LAST:event_jbSimularCongruenciaActionPerformed

    private void jbSimularUniformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimularUniformeActionPerformed

        int cantDeValores = Integer.parseInt(jtNumAGenerarUniforme.getText());

        double a = Double.parseDouble(jtfUniformeA.getText());
        double b = Double.parseDouble(jtfUniformeB.getText());

        double[] numerosAleatorios = g.uniforme(cantDeValores, a, b);
        Object[] listaObject = pasarALista(cantDeValores, numerosAleatorios);
        jlNumerosAleatoriosGenerados.setListData(listaObject);

        graficarHistograma(calcularHistograma(numerosAleatorios,
                Integer.parseInt(jcbIntervalosUniforme.getSelectedItem().toString()),
                false));

    }//GEN-LAST:event_jbSimularUniformeActionPerformed

    private DefaultCategoryDataset calcularHistograma(double[] numerosAleatorios, int cantIntervalos, boolean esContinua) {

        double[] valoresDeFrecuencia = g.calcularValoresDeFrecuencia(numerosAleatorios, cantIntervalos, esContinua);
        int[] cantidadXintervalo = new int[valoresDeFrecuencia.length - 1];

        for (int i = 0; i < cantidadXintervalo.length; i++) {
            cantidadXintervalo[i] = 0;
        }

        for (int i = 0; i < numerosAleatorios.length; i++) {
            double j = numerosAleatorios[i];

            for (int k = 1; k < valoresDeFrecuencia.length; k++) {
                if (j >= valoresDeFrecuencia[k - 1] && j < valoresDeFrecuencia[k]) {
                    cantidadXintervalo[k - 1]++;
                }
            }
        }
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        for (int i = 1; i < valoresDeFrecuencia.length; i++) {
            if (esContinua) {
                dataset.addValue(cantidadXintervalo[i - 1], "Frecuencia", "" + valoresDeFrecuencia[i]);
            } else {
                dataset.addValue(cantidadXintervalo[i - 1], "Frecuencia", "" + valoresDeFrecuencia[i - 1] + " - " + valoresDeFrecuencia[i]);
            }
        }

        return dataset;

    }

    private void graficarHistograma(DefaultCategoryDataset dataset) {


        JFreeChart chart = ChartFactory.createBarChart(
                "Histograma", // chart title
                "Intervalos de Clase", // domain axis label
                "Frecuencia Absoluta", // range axis label
                dataset, // data
                PlotOrientation.VERTICAL, // orientation
                false, // include legend
                false, // tooltips?
                false // URLs?
                );



        ChartPanel chartPanel = new ChartPanel(chart, false);
        //chartPanel.setPreferredSize(new Dimension(500, 270));
        jfHistograma.setContentPane(chartPanel);
        jfHistograma.pack();
        jfHistograma.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JButton jbSimularCongruencia;
    private javax.swing.JButton jbSimularExponencial;
    private javax.swing.JButton jbSimularNormal;
    private javax.swing.JButton jbSimularPoisson;
    private javax.swing.JButton jbSimularUniforme;
    private javax.swing.JComboBox jcbIntervalosCongruencia;
    private javax.swing.JComboBox jcbIntervalosExponencial;
    private javax.swing.JComboBox jcbIntervalosNormal;
    private javax.swing.JComboBox jcbIntervalosPoisson;
    private javax.swing.JComboBox jcbIntervalosUniforme;
    private javax.swing.JInternalFrame jfHistograma;
    private javax.swing.JList jlNumerosAleatoriosGenerados;
    private javax.swing.JRadioButton jrbAditiva;
    private javax.swing.JRadioButton jrbMixta;
    private javax.swing.JRadioButton jrbMultiplicativa;
    private javax.swing.JRadioButton jrbSenoCoseno;
    private javax.swing.JRadioButton jrbSumatoria;
    private javax.swing.JTextField jtNumAGenerarCongruencia;
    private javax.swing.JTextField jtNumAGenerarExponencial;
    private javax.swing.JTextField jtNumAGenerarNormal;
    private javax.swing.JTextField jtNumAGenerarPoisson;
    private javax.swing.JTextField jtNumAGenerarUniforme;
    private javax.swing.JTextField jtfASemilla;
    private javax.swing.JTextField jtfAb;
    private javax.swing.JTextField jtfAm;
    private javax.swing.JTextField jtfMixA;
    private javax.swing.JTextField jtfMixB;
    private javax.swing.JTextField jtfMixM;
    private javax.swing.JTextField jtfMixSemilla;
    private javax.swing.JTextField jtfMulA;
    private javax.swing.JTextField jtfMulM;
    private javax.swing.JTextField jtfMulSemilla;
    private javax.swing.JTextField jtfUniformeA;
    private javax.swing.JTextField jtfUniformeB;
    private javax.swing.JLabel lCant;
    private javax.swing.JTextArea taSenCosen;
    private javax.swing.JTextArea taSumatoria;
    private javax.swing.JTextField tfCantValoresSumatoria;
    private javax.swing.JTextField tfMediaExponencial;
    private javax.swing.JTextField tfMediaPoisson;
    // End of variables declaration//GEN-END:variables
}
